-- Portal Integrado N2 — fluxo administrativo, auditoria e notificações
-- Migração idempotente: pode ser executada novamente sem apagar dados.

create sequence if not exists public.portal_protocolo_seq start 1;

create or replace function public.portal_gerar_protocolo(prefixo text)
returns text
language sql
volatile
security definer
set search_path = public
as $$
  select upper(prefixo)
    || '-' || to_char(current_date, 'YYYY')
    || '-' || lpad(nextval('public.portal_protocolo_seq')::text, 6, '0');
$$;

alter table public.oficios
  add column if not exists protocolo text,
  add column if not exists prioridade text default 'NORMAL',
  add column if not exists etapa text default 'TRIAGEM',
  add column if not exists descricao text,
  add column if not exists interessado text,
  add column if not exists sigilo text default 'PUBLICO',
  add column if not exists justificativa_gestor text,
  add column if not exists criado_por_matricula text,
  add column if not exists atualizado_por_matricula text,
  add column if not exists atualizado_por_nome text,
  add column if not exists updated_at timestamptz default now(),
  add column if not exists assinado_em timestamptz,
  add column if not exists assinatura_hash text;

alter table public.solicitacoes_almoxarifado
  add column if not exists protocolo text,
  add column if not exists prioridade text default 'NORMAL',
  add column if not exists justificativa_gestor text,
  add column if not exists atualizado_por_matricula text,
  add column if not exists atualizado_por_nome text,
  add column if not exists updated_at timestamptz default now();

alter table public.solicitacoes_frota
  add column if not exists protocolo text,
  add column if not exists prioridade text default 'NORMAL',
  add column if not exists justificativa_gestor text,
  add column if not exists atualizado_por_matricula text,
  add column if not exists atualizado_por_nome text,
  add column if not exists updated_at timestamptz default now();

alter table public.chamados_patrimonio
  add column if not exists protocolo text,
  add column if not exists prioridade text default 'NORMAL',
  add column if not exists justificativa_gestor text,
  add column if not exists atualizado_por_matricula text,
  add column if not exists atualizado_por_nome text,
  add column if not exists updated_at timestamptz default now();

create table if not exists public.solicitacoes_ferias (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  protocolo text unique,
  matricula text not null,
  nome_servidor text not null,
  uorg text,
  data_inicio text not null,
  data_fim text not null,
  data_retorno text not null,
  quantidade_dias integer not null,
  funcao_chefia boolean not null default false,
  prioridade text not null default 'NORMAL',
  status text not null default 'EM_ANALISE',
  justificativa_gestor text,
  atualizado_por_matricula text,
  atualizado_por_nome text
);

create table if not exists public.auditoria_eventos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tabela text not null,
  registro_id text not null,
  protocolo text,
  acao text not null,
  status_anterior text,
  status_novo text,
  usuario_matricula text,
  usuario_nome text,
  detalhes jsonb not null default '{}'::jsonb
);

create table if not exists public.notificacoes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  matricula text not null,
  titulo text not null,
  mensagem text not null,
  modulo text not null,
  protocolo text,
  lida boolean not null default false
);

create unique index if not exists oficios_protocolo_uidx
  on public.oficios (protocolo) where protocolo is not null;
create unique index if not exists almoxarifado_protocolo_uidx
  on public.solicitacoes_almoxarifado (protocolo) where protocolo is not null;
create unique index if not exists frota_protocolo_uidx
  on public.solicitacoes_frota (protocolo) where protocolo is not null;
create unique index if not exists patrimonio_protocolo_uidx
  on public.chamados_patrimonio (protocolo) where protocolo is not null;
create index if not exists auditoria_registro_idx
  on public.auditoria_eventos (tabela, registro_id, created_at desc);
create index if not exists notificacoes_matricula_idx
  on public.notificacoes (matricula, lida, created_at desc);

update public.oficios
set protocolo = public.portal_gerar_protocolo('GAB')
where protocolo is null;

update public.solicitacoes_almoxarifado
set protocolo = public.portal_gerar_protocolo('ALM')
where protocolo is null;

update public.solicitacoes_frota
set protocolo = public.portal_gerar_protocolo('FRO')
where protocolo is null;

update public.chamados_patrimonio
set protocolo = public.portal_gerar_protocolo('PAT')
where protocolo is null;

create or replace function public.portal_preparar_fluxo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  prefixo text;
begin
  prefixo := case tg_table_name
    when 'oficios' then 'GAB'
    when 'solicitacoes_almoxarifado' then 'ALM'
    when 'solicitacoes_frota' then 'FRO'
    when 'chamados_patrimonio' then 'PAT'
    when 'solicitacoes_ferias' then 'FER'
    else 'PRC'
  end;

  if new.protocolo is null or btrim(new.protocolo) = '' then
    new.protocolo := public.portal_gerar_protocolo(prefixo);
  end if;

  if new.prioridade is null or btrim(new.prioridade) = '' then
    new.prioridade := 'NORMAL';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.portal_auditar_fluxo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  novo jsonb := to_jsonb(new);
  antigo jsonb := case when tg_op = 'UPDATE' then to_jsonb(old) else '{}'::jsonb end;
  acao_evento text;
  matricula_ator text;
  nome_ator text;
  matricula_destino text;
  status_anterior text;
  status_novo text;
begin
  matricula_ator := coalesce(
    novo ->> 'atualizado_por_matricula',
    novo ->> 'criado_por_matricula',
    novo ->> 'matricula'
  );
  nome_ator := coalesce(
    novo ->> 'atualizado_por_nome',
    novo ->> 'nome_servidor',
    novo ->> 'responsavel'
  );
  matricula_destino := coalesce(novo ->> 'matricula', novo ->> 'criado_por_matricula');
  status_anterior := antigo ->> 'status';
  status_novo := novo ->> 'status';

  if tg_op = 'INSERT' then
    acao_evento := 'CRIACAO';
  elsif status_anterior is distinct from status_novo then
    acao_evento := 'ALTERACAO_STATUS';
  else
    acao_evento := 'ATUALIZACAO';
  end if;

  insert into public.auditoria_eventos (
    tabela, registro_id, protocolo, acao, status_anterior, status_novo,
    usuario_matricula, usuario_nome, detalhes
  ) values (
    tg_table_name,
    coalesce(novo ->> 'id', 'sem-id'),
    novo ->> 'protocolo',
    acao_evento,
    status_anterior,
    status_novo,
    matricula_ator,
    nome_ator,
    jsonb_build_object('prioridade', novo ->> 'prioridade')
  );

  if tg_op = 'UPDATE'
     and status_anterior is distinct from status_novo
     and matricula_destino is not null then
    insert into public.notificacoes (matricula, titulo, mensagem, modulo, protocolo)
    values (
      matricula_destino,
      'Atualização de solicitação',
      'O status foi alterado de ' || coalesce(status_anterior, 'não informado')
        || ' para ' || coalesce(status_novo, 'não informado') || '.',
      tg_table_name,
      novo ->> 'protocolo'
    );
  end if;

  return new;
end;
$$;

do $$
declare
  tabela_nome text;
begin
  foreach tabela_nome in array array[
    'oficios',
    'solicitacoes_almoxarifado',
    'solicitacoes_frota',
    'chamados_patrimonio',
    'solicitacoes_ferias'
  ] loop
    execute format('drop trigger if exists portal_preparar_fluxo_trg on public.%I', tabela_nome);
    execute format(
      'create trigger portal_preparar_fluxo_trg before insert or update on public.%I for each row execute function public.portal_preparar_fluxo()',
      tabela_nome
    );
    execute format('drop trigger if exists portal_auditar_fluxo_trg on public.%I', tabela_nome);
    execute format(
      'create trigger portal_auditar_fluxo_trg after insert or update on public.%I for each row execute function public.portal_auditar_fluxo()',
      tabela_nome
    );
  end loop;
end $$;

-- O acesso permanece fechado até a migração de sessão e RLS granular.
-- Isso evita uma janela com CRUD público durante instalações novas.
alter table public.oficios enable row level security;
alter table public.solicitacoes_almoxarifado enable row level security;
alter table public.solicitacoes_frota enable row level security;
alter table public.chamados_patrimonio enable row level security;
alter table public.solicitacoes_ferias enable row level security;
alter table public.auditoria_eventos enable row level security;
alter table public.notificacoes enable row level security;

revoke all on public.oficios from anon, authenticated;
revoke all on public.solicitacoes_almoxarifado from anon, authenticated;
revoke all on public.solicitacoes_frota from anon, authenticated;
revoke all on public.chamados_patrimonio from anon, authenticated;
revoke all on public.solicitacoes_ferias from anon, authenticated;
revoke all on public.auditoria_eventos from anon, authenticated;
revoke all on public.notificacoes from anon, authenticated;
revoke all on sequence public.portal_protocolo_seq from anon, authenticated;

notify pgrst, 'reload schema';
