-- Portal Integrado N2 — sessão temporária e RLS por matrícula/perfil.
-- Corrige instalações que receberam as políticas amplas da migração anterior.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.portal_sessoes (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  matricula text not null,
  cpf text not null,
  nome text not null,
  cargo text not null,
  uorg_id text not null,
  nivel_acesso text not null default 'OURO',
  criado_em timestamptz not null default now(),
  expira_em timestamptz not null,
  ultimo_uso_em timestamptz not null default now()
);

create index if not exists portal_sessoes_expira_idx
  on public.portal_sessoes (expira_em);

alter table public.auditoria_eventos
  add column if not exists destinatario_matricula text;

create or replace function public.portal_token_requisicao()
returns text
language plpgsql
stable
set search_path = public, pg_temp
as $$
declare
  cabecalhos text;
begin
  cabecalhos := current_setting('request.headers', true);
  if cabecalhos is null or cabecalhos = '' then
    return null;
  end if;
  return nullif(cabecalhos::jsonb ->> 'x-portal-session', '');
exception when others then
  return null;
end;
$$;

create or replace function public.portal_sessao_atual()
returns table (
  matricula text,
  cpf text,
  nome text,
  cargo text,
  uorg_id text,
  nivel_acesso text
)
language sql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
  select
    s.matricula,
    s.cpf,
    s.nome,
    s.cargo,
    s.uorg_id,
    s.nivel_acesso
  from public.portal_sessoes s
  where s.token_hash = encode(
    extensions.digest(public.portal_token_requisicao(), 'sha256'),
    'hex'
  )
    and s.expira_em > now()
  limit 1;
$$;

create or replace function public.portal_matricula_atual()
returns text
language sql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
  select s.matricula from public.portal_sessao_atual() s limit 1;
$$;

create or replace function public.portal_nome_atual()
returns text
language sql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
  select s.nome from public.portal_sessao_atual() s limit 1;
$$;

create or replace function public.portal_eh_gestor()
returns boolean
language sql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
  select coalesce(
    (select upper(s.nivel_acesso) = 'DIAMANTE'
     from public.portal_sessao_atual() s
     limit 1),
    false
  );
$$;

create or replace function public.portal_iniciar_sessao(p_cpf text)
returns table (
  session_token text,
  cpf text,
  nome text,
  cargo text,
  uorg_id text,
  matricula text,
  nivel_acesso text,
  expira_em timestamptz
)
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  cpf_limpo text := regexp_replace(coalesce(p_cpf, ''), '[^0-9]', '', 'g');
  servidor public.servidores%rowtype;
  token_aberto text;
  validade timestamptz := now() + interval '8 hours';
begin
  if length(cpf_limpo) <> 11 then
    return;
  end if;

  select s.* into servidor
  from public.servidores s
  where regexp_replace(s.cpf::text, '[^0-9]', '', 'g') = cpf_limpo
  limit 1;

  if not found then
    return;
  end if;

  delete from public.portal_sessoes s
  where s.expira_em <= now()
     or (s.matricula = servidor.matricula::text and s.criado_em < now() - interval '1 hour');

  token_aberto := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public.portal_sessoes (
    token_hash, matricula, cpf, nome, cargo, uorg_id, nivel_acesso, expira_em
  ) values (
    encode(extensions.digest(token_aberto, 'sha256'), 'hex'),
    servidor.matricula::text,
    servidor.cpf::text,
    servidor.nome::text,
    servidor.cargo::text,
    servidor.uorg_id::text,
    coalesce(servidor.nivel_acesso::text, 'OURO'),
    validade
  );

  return query select
    token_aberto,
    servidor.cpf::text,
    servidor.nome::text,
    servidor.cargo::text,
    servidor.uorg_id::text,
    servidor.matricula::text,
    coalesce(servidor.nivel_acesso::text, 'OURO'),
    validade;
end;
$$;

create or replace function public.portal_perfil_atual()
returns table (
  cpf text,
  nome text,
  cargo text,
  uorg_id text,
  matricula text,
  nivel_acesso text
)
language sql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
  select s.cpf, s.nome, s.cargo, s.uorg_id, s.matricula, s.nivel_acesso
  from public.portal_sessao_atual() s;
$$;

create or replace function public.portal_aplicar_identidade()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  matricula_sessao text := public.portal_matricula_atual();
  nome_sessao text := public.portal_nome_atual();
  gestor boolean := public.portal_eh_gestor();
begin
  if matricula_sessao is null then
    raise exception 'Sessão do Portal inválida ou expirada'
      using errcode = '42501';
  end if;

  if tg_table_name = 'oficios' then
    if not gestor then
      raise exception 'Operação exclusiva do perfil DIAMANTE'
        using errcode = '42501';
    end if;

    if tg_op = 'INSERT' then
      new.criado_por_matricula := matricula_sessao;
    else
      new.criado_por_matricula := old.criado_por_matricula;
    end if;
  else
    if tg_op = 'INSERT' then
      new.matricula := matricula_sessao;
      new.nome_servidor := nome_sessao;
    else
      if not gestor then
        raise exception 'Atualização exclusiva do perfil DIAMANTE'
          using errcode = '42501';
      end if;
      new.matricula := old.matricula;
      new.nome_servidor := old.nome_servidor;
    end if;
  end if;

  new.atualizado_por_matricula := matricula_sessao;
  new.atualizado_por_nome := nome_sessao;
  return new;
end;
$$;

create or replace function public.portal_auditar_fluxo()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  novo jsonb := to_jsonb(new);
  antigo jsonb := case when tg_op = 'UPDATE' then to_jsonb(old) else '{}'::jsonb end;
  acao_evento text;
  matricula_ator text;
  nome_ator text;
  matricula_destino text;
  status_anterior text;
  status_novo text;
begin
  matricula_ator := coalesce(
    novo ->> 'atualizado_por_matricula',
    novo ->> 'criado_por_matricula',
    novo ->> 'matricula'
  );
  nome_ator := coalesce(
    novo ->> 'atualizado_por_nome',
    novo ->> 'nome_servidor',
    novo ->> 'responsavel'
  );
  matricula_destino := coalesce(novo ->> 'matricula', novo ->> 'criado_por_matricula');
  status_anterior := antigo ->> 'status';
  status_novo := novo ->> 'status';

  if tg_op = 'INSERT' then
    acao_evento := 'CRIACAO';
  elsif status_anterior is distinct from status_novo then
    acao_evento := 'ALTERACAO_STATUS';
  else
    acao_evento := 'ATUALIZACAO';
  end if;

  insert into public.auditoria_eventos (
    tabela, registro_id, protocolo, acao, status_anterior, status_novo,
    usuario_matricula, usuario_nome, destinatario_matricula, detalhes
  ) values (
    tg_table_name,
    coalesce(novo ->> 'id', 'sem-id'),
    novo ->> 'protocolo',
    acao_evento,
    status_anterior,
    status_novo,
    matricula_ator,
    nome_ator,
    matricula_destino,
    jsonb_build_object('prioridade', novo ->> 'prioridade')
  );

  if tg_op = 'UPDATE'
     and status_anterior is distinct from status_novo
     and matricula_destino is not null then
    insert into public.notificacoes (matricula, titulo, mensagem, modulo, protocolo)
    values (
      matricula_destino,
      'Atualização de solicitação',
      'O status foi alterado de ' || coalesce(status_anterior, 'não informado')
        || ' para ' || coalesce(status_novo, 'não informado') || '.',
      tg_table_name,
      novo ->> 'protocolo'
    );
  end if;

  return new;
end;
$$;

do $$
declare
  tabela_nome text;
begin
  foreach tabela_nome in array array[
    'oficios',
    'solicitacoes_almoxarifado',
    'solicitacoes_frota',
    'chamados_patrimonio',
    'solicitacoes_ferias'
  ] loop
    execute format('drop trigger if exists portal_identidade_trg on public.%I', tabela_nome);
    execute format(
      'create trigger portal_identidade_trg before insert or update on public.%I for each row execute function public.portal_aplicar_identidade()',
      tabela_nome
    );
  end loop;
end $$;

alter table public.servidores enable row level security;
alter table public.contracheques enable row level security;
alter table public.oficios enable row level security;
alter table public.solicitacoes_almoxarifado enable row level security;
alter table public.solicitacoes_frota enable row level security;
alter table public.chamados_patrimonio enable row level security;
alter table public.solicitacoes_ferias enable row level security;
alter table public.auditoria_eventos enable row level security;
alter table public.notificacoes enable row level security;
alter table public.portal_sessoes enable row level security;

do $$
declare
  tabela_nome text;
  politica record;
begin
  foreach tabela_nome in array array[
    'servidores',
    'contracheques',
    'oficios',
    'solicitacoes_almoxarifado',
    'solicitacoes_frota',
    'chamados_patrimonio',
    'solicitacoes_ferias',
    'auditoria_eventos',
    'notificacoes',
    'portal_sessoes'
  ] loop
    for politica in
      select policyname
      from pg_policies
      where schemaname = 'public' and tablename = tabela_nome
    loop
      execute format('drop policy if exists %I on public.%I', politica.policyname, tabela_nome);
    end loop;
  end loop;
end $$;

create policy contracheques_proprios_select
  on public.contracheques
  for select to anon, authenticated
  using (matricula::text = public.portal_matricula_atual());

create policy oficios_gestor_select
  on public.oficios
  for select to anon, authenticated
  using (
    public.portal_eh_gestor()
    or criado_por_matricula = public.portal_matricula_atual()
  );

create policy oficios_gestor_insert
  on public.oficios
  for insert to anon, authenticated
  with check (
    public.portal_eh_gestor()
    and criado_por_matricula = public.portal_matricula_atual()
  );

create policy oficios_gestor_update
  on public.oficios
  for update to anon, authenticated
  using (public.portal_eh_gestor())
  with check (public.portal_eh_gestor());

do $$
declare
  tabela_nome text;
begin
  foreach tabela_nome in array array[
    'solicitacoes_almoxarifado',
    'solicitacoes_frota',
    'chamados_patrimonio',
    'solicitacoes_ferias'
  ] loop
    execute format(
      'create policy portal_proprio_ou_gestor_select on public.%I for select to anon, authenticated using (matricula::text = public.portal_matricula_atual() or public.portal_eh_gestor())',
      tabela_nome
    );
    execute format(
      'create policy portal_proprio_insert on public.%I for insert to anon, authenticated with check (matricula::text = public.portal_matricula_atual())',
      tabela_nome
    );
    execute format(
      'create policy portal_gestor_update on public.%I for update to anon, authenticated using (public.portal_eh_gestor()) with check (public.portal_eh_gestor())',
      tabela_nome
    );
  end loop;
end $$;

create policy auditoria_propria_ou_gestor_select
  on public.auditoria_eventos
  for select to anon, authenticated
  using (
    public.portal_eh_gestor()
    or usuario_matricula = public.portal_matricula_atual()
    or destinatario_matricula = public.portal_matricula_atual()
  );

create policy notificacoes_proprias_select
  on public.notificacoes
  for select to anon, authenticated
  using (matricula = public.portal_matricula_atual());

create policy notificacoes_proprias_update
  on public.notificacoes
  for update to anon, authenticated
  using (matricula = public.portal_matricula_atual())
  with check (matricula = public.portal_matricula_atual());

revoke all on table public.servidores from anon, authenticated;
revoke all on table public.contracheques from anon, authenticated;
revoke all on table public.oficios from anon, authenticated;
revoke all on table public.solicitacoes_almoxarifado from anon, authenticated;
revoke all on table public.solicitacoes_frota from anon, authenticated;
revoke all on table public.chamados_patrimonio from anon, authenticated;
revoke all on table public.solicitacoes_ferias from anon, authenticated;
revoke all on table public.auditoria_eventos from anon, authenticated;
revoke all on table public.notificacoes from anon, authenticated;
revoke all on table public.portal_sessoes from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select on table public.contracheques to anon, authenticated;
grant select, insert, update on table public.oficios to anon, authenticated;
grant select, insert, update on table public.solicitacoes_almoxarifado to anon, authenticated;
grant select, insert, update on table public.solicitacoes_frota to anon, authenticated;
grant select, insert, update on table public.chamados_patrimonio to anon, authenticated;
grant select, insert, update on table public.solicitacoes_ferias to anon, authenticated;
grant select on table public.auditoria_eventos to anon, authenticated;
grant select on table public.notificacoes to anon, authenticated;
grant update (lida) on table public.notificacoes to anon, authenticated;

do $$
declare
  tabela_nome text;
  sequencia_nome text;
begin
  foreach tabela_nome in array array[
    'oficios',
    'solicitacoes_almoxarifado',
    'solicitacoes_frota',
    'chamados_patrimonio',
    'solicitacoes_ferias'
  ] loop
    sequencia_nome := pg_get_serial_sequence('public.' || tabela_nome, 'id');
    if sequencia_nome is not null then
      execute format(
        'grant usage, select on sequence %s to anon, authenticated',
        sequencia_nome::regclass
      );
    end if;
  end loop;
end $$;

revoke all on function public.portal_gerar_protocolo(text) from public, anon, authenticated;
revoke all on function public.portal_preparar_fluxo() from public, anon, authenticated;
revoke all on function public.portal_auditar_fluxo() from public, anon, authenticated;
revoke all on function public.portal_aplicar_identidade() from public, anon, authenticated;
revoke all on function public.portal_iniciar_sessao(text) from public, anon, authenticated;
revoke all on function public.portal_perfil_atual() from public, anon, authenticated;
revoke all on function public.portal_token_requisicao() from public, anon, authenticated;
revoke all on function public.portal_sessao_atual() from public, anon, authenticated;
revoke all on function public.portal_matricula_atual() from public, anon, authenticated;
revoke all on function public.portal_nome_atual() from public, anon, authenticated;
revoke all on function public.portal_eh_gestor() from public, anon, authenticated;

grant execute on function public.portal_iniciar_sessao(text) to anon, authenticated;
grant execute on function public.portal_perfil_atual() to anon, authenticated;
grant execute on function public.portal_token_requisicao() to anon, authenticated;
grant execute on function public.portal_sessao_atual() to anon, authenticated;
grant execute on function public.portal_matricula_atual() to anon, authenticated;
grant execute on function public.portal_nome_atual() to anon, authenticated;
grant execute on function public.portal_eh_gestor() to anon, authenticated;

notify pgrst, 'reload schema';
